#!/usr/bin/python

"""
Custom topology for Mininet, generated by GraphML-Topo-to-Mininet-Network-Generator.
"""
from mininet.topo import Topo
from mininet.net import Mininet
from mininet.node import RemoteController
from mininet.node import Node
from mininet.node import CPULimitedHost
from mininet.node import OVSSwitch
from mininet.link import TCLink
from mininet.cli import CLI
from mininet.log import setLogLevel
from mininet.util import dumpNodeConnections
from functools import partial

class GeneratedTopo( Topo ):
    "Internet Topology Zoo Specimen."

    def __init__( self, **opts ):
        "Create a topology."

        # Initialize Topology
        Topo.__init__( self, **opts )

        # add nodes, switches first...
        NewYork = self.addSwitch( 's0', dpid='0000000000000001')
        Chicago = self.addSwitch( 's1', dpid='0000000000000002') 
        WashingtonDC = self.addSwitch( 's2', dpid='0000000000000003')
        KansasCity = self.addSwitch( 's3', dpid='0000000000000004' )
        Houston = self.addSwitch( 's4', dpid='0000000000000005' )
        Atlanta = self.addSwitch( 's5', dpid='0000000000000006' )
        Indianapolis = self.addSwitch( 's6', dpid='0000000000000007' )

        # ... and now hosts
        NewYork_host = self.addHost( 'h1', mac='92:61:8D:5F:F5:20' )
        WashingtonDC_host1 = self.addHost( 'h2', mac='D2:B2:87:4F:6D:03' )
        WashingtonDC_host2 = self.addHost( 'h3', mac='D2:B2:87:4F:6D:04' )
        KansasCity_host = self.addHost( 'h4', mac='7A:B0:67:5E:D0:61' )
        Houston_host = self.addHost( 'h5', mac='BE:A2:20:6C:2C:D4' )
        Atlanta_host = self.addHost( 'h6', mac='EA:9B:1E:3C:43:5A' )

        # add edges between switch and corresponding host
        self.addLink( NewYork , NewYork_host )
        self.addLink( Chicago , WashingtonDC_host1 )
        self.addLink( Chicago , WashingtonDC_host2 )
        self.addLink( KansasCity , KansasCity_host )
        self.addLink( Houston , Houston_host )
        self.addLink( Indianapolis , Atlanta_host )

        # add edges between switches
        self.addLink( NewYork , Chicago, bw=1000, delay='0.806374975652ms')
        self.addLink( NewYork , WashingtonDC, bw=1000, delay='0.605826192092ms')
        self.addLink( Chicago , Indianapolis, bw=1000, delay='1.34462717203ms')
        self.addLink( WashingtonDC , Atlanta, bw=1000, delay='0.557636936322ms')
        self.addLink( KansasCity , Houston, bw=1000, delay='1.71325092726ms')
        self.addLink( KansasCity , Indianapolis, bw=1000, delay='0.240899959477ms')
        self.addLink( Houston , Atlanta, bw=1000, delay='1.34344500256ms')

topos = { 'generated': ( lambda: GeneratedTopo() ) }

# HERE THE CODE DEFINITION OF THE TOPOLOGY ENDS

# the following code produces an executable script working with a remote controller
# and providing ssh access to the the mininet hosts from within the ubuntu vm
controller_ip = '192.168.0.101'

def setupNetwork(controller_ip):
    "Create network and run simple performance test"
    # check if remote controller's ip was set
    # else set it to localhost
    topo = GeneratedTopo()
    if controller_ip == '':
        #controller_ip = '10.0.2.2';
        controller_ip = '127.0.0.1';
    OVSSwitch13 = partial( OVSSwitch, protocols='OpenFlow13')
    net = Mininet(topo=topo, controller=lambda a: RemoteController( a, ip=controller_ip, port=6633 ), host=CPULimitedHost, link=TCLink, switch=OVSSwitch13)
    return net

def connectToRootNS( network, switch, ip, prefixLen, routes ):
    "Connect hosts to root namespace via switch. Starts network."
    "network: Mininet() network object"
    "switch: switch to connect to root namespace"
    "ip: IP address for root namespace node"
    "prefixLen: IP address prefix length (e.g. 8, 16, 24)"
    "routes: host networks to route to"
    # Create a node in root namespace and link to switch 0
    root = Node( 'root', inNamespace=False )
    intf = TCLink( root, switch ).intf1
    root.setIP( ip, prefixLen, intf )
    # Start network that now includes link to root namespace
    network.start()
    # Add routes from root ns to hosts
    for route in routes:
        root.cmd( 'route add -net ' + route + ' dev ' + str( intf ) )

def sshd( network, cmd='/usr/sbin/sshd', opts='-D' ):
    "Start a network, connect it to root ns, and run sshd on all hosts."
    switch = network.switches[ 0 ]  # switch to use
    ip = '10.123.123.1'  # our IP address on host network
    routes = [ '10.0.0.0/8' ]  # host networks to route to
    connectToRootNS( network, switch, ip, 8, routes )
    for host in network.hosts:
        host.cmd( cmd + ' ' + opts + '&' )

    # DEBUGGING INFO
    print
    print "Dumping host connections"
    dumpNodeConnections(network.hosts)
    print
    print "*** Hosts are running sshd at the following addresses:"
    print
    for host in network.hosts:
        print host.name, host.IP()
    print
    print "*** Type 'exit' or control-D to shut down network"
    print
    print "*** For testing network connectivity among the hosts, wait a bit for the controller to create all the routes, then do 'pingall' on the mininet console."
    print

    CLI( network )
    for host in network.hosts:
        host.cmd( 'kill %' + cmd )
    network.stop()


if __name__ == '__main__':
    setLogLevel('info')
    #setLogLevel('debug')
    sshd( setupNetwork(controller_ip) )
