#!/bin/bash
#
# An example of the Athena configuration file on a single environment
# by Jinwoo Kim

# unset all variables
unset $(env | sed -n 's:\(^OC[0-9]\{1,\}\)=.*:\1 :g p')
unset $(env | sed -n 's:\(^MD[0-9]\{1,\}\)=.*:\1 :g p')
unset $(env | sed -n 's:\(^SP[0-9]\{1,\}\)=.*:\1 :g p')

# the mode for an Athena environment e.g. SINGLE or DISTRIBUTED
export MODE="DISTRIBUTED"

# the addresses of ONOS instances
export OC1="10.0.3.22"
export OC2="10.0.3.158"
export OC3="10.0.3.108"

# the addressees of the MongoDB containers
export MD1="10.0.3.112"
export MD2="10.0.3.176"
export MD3="10.0.3.115"

# the addressees of the Spark containers
export SP1="10.0.3.226"
export SP2="10.0.3.63"
export SP3="10.0.3.60"

# the path of Athena
export ATHENA_ROOT=~/athena-1.6

# the parameters for ONOS
export ONOS_APPS="drivers,openflow,proxyarp,mobility,fwd"
ONOS_WEB_PASS=karaf
ONOS_WEB_USER=karaf