package org.onosproject.athena.feature;

import org.onosproject.net.provider.ProviderService;

/**
 * Created by seunghyeon on 8/26/15.
 */
public interface FeatureCollectorProviderService extends ProviderService<FeatureCollectorProvider> {

    /**
     * Packet_In feature handler called by provider service.
     *
     * @param packetInFeature Generated by FeatureCollectorProvider
     */
    void packetInFeatureHandler(PacketInFeature packetInFeature);

    /**
     * Flow Removed feature handler called by provider service.
     *
     * @param flowRemovedFeature Generated by FeatureCollectorProvider
     */
    void flowRemovedHandler(FlowRemovedFeature flowRemovedFeature);

    /**
     * Port Status feature handler called by provider service.
     *
     * @param portStatusFeature Generated by FeatureCollectorProvider
     */
    void portStatusHandler(PortStatusFeature portStatusFeature);

    /**
     * Error Message feature handler called by provider service.
     *
     * @param errorMessageFeature Generated by FeatureCollectorProvider
     */
    void errorMsgHandler(ErrorMessageFeature errorMessageFeature);

    /**
     * Flow statistics feature handler called by provider service.
     *
     * @param flowStatisticsFeature Generated by FeatureCollectorProvider
     */
    void flowStatsHandler(FlowStatisticsFeature flowStatisticsFeature);

    /**
     * Aggregate statistics feature handler called by provider service.
     *
     * @param aggregateStatisticsFeature Generated by FeatureCollectorProvider
     */
    void aggregateStatsHandler(AggregateStatisticsFeature aggregateStatisticsFeature);

    /**
     * Port statistics feature handler called by provider service.
     *
     * @param portStatisticsFeature Generated by FeatureCollectorProvider
     */
    void portStatsHandler(PortStatisticsFeature portStatisticsFeature);

    /**
     * Queue statistics feature handler called by provider service.
     *
     * @param queueStatisticsFeature Generated by FeatureCollectorProvider
     */
    void queueStatsHandler(QueueStatisticsFeature queueStatisticsFeature);

    /**
     * Table statistics feature handler called by provider service.
     *
     * @param tableStatisticsFeature Generated by FeatureCollectorProvider
     */
    void tableStatsHandler(TableStatisticsFeature tableStatisticsFeature);
}
